In [79]:
import pandas as pd
import seaborn as sns
import numpy as np 
from sklearn.model_selection import train_test_split

In [80]:
df = pd.read_csv("players_15.csv")
df

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2           9014  https://sofifa.com/player/9014/arjen-robben/15...   
3          41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4         167495  https://sofifa.com/player/167495/manuel-neuer/...   
...          ...                                                ...   
15460     220806  https://sofifa.com/player/220806/ellis-redman/...   
15461     225509  https://sofifa.com/player/225509/aaron-collins...   
15462     217591  https://sofifa.com/player/217591/piotr-zemlo/1...   
15463     222947  https://sofifa.com/player/222947/tom-davies/15...   
15464     201197  https://sofifa.com/player/201197/paul-tisdale/...   

              short_name                            long_name  age  \
0               L. Messi       Lionel Andrés Messi Cuccittini   27   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   29   
2              A. Robben                         Arjen Robben   30   
3         Z. Ibrahimović                   Zlatan Ibrahimović   32   
4               M. Neuer                         Manuel Neuer   28   
...                  ...                                  ...  ...   
15460          E. Redman                         Ellis Redman   17   
15461         A. Collins                        Aaron Collins   17   
15462           P. Żemło                          Piotr Żemło   18   
15463          T. Davies                           Tom Davies   22   
15464         P. Tisdale                         Paul Tisdale   41   

              dob  height_cm  weight_kg  nationality                 club  \
0      1987-06-24        169         67    Argentina         FC Barcelona   
1      1985-02-05        185         80     Portugal          Real Madrid   
2      1984-01-23        180         80  Netherlands    FC Bayern München   
3      1981-10-03        195         95       Sweden  Paris Saint-Germain   
4      1986-03-27        193         92      Germany    FC Bayern München   
...           ...        ...        ...          ...                  ...   
15460  1996-09-26        187         81        Wales       Newport County   
15461  1997-06-01        178         57        Wales       Newport County   
15462  1995-07-10        190         76       Poland         Wisła Kraków   
15463  1992-04-18        180         70      England       Fleetwood Town   
15464  1973-01-14        175         72        Malta          Exeter City   

       ...   lwb   ldm   cdm   rdm   rwb    lb   lcb    cb   rcb    rb  
0      ...  62+3  62+3  62+3  62+3  62+3  54+3  45+3  45+3  45+3  54+3  
1      ...  63+3  63+3  63+3  63+3  63+3  57+3  52+3  52+3  52+3  57+3  
2      ...  64+3  64+3  64+3  64+3  64+3  55+3  46+3  46+3  46+3  55+3  
3      ...  61+3  65+3  65+3  65+3  61+3  56+3  55+3  55+3  55+3  56+3  
4      ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
15460  ...  37+0  38+0  38+0  38+0  37+0  40+0  41+0  41+0  41+0  40+0  
15461  ...  31+0  30+0  30+0  30+0  31+0  32+0  31+0  31+0  31+0  32+0  
15462  ...  48+0  46+0  46+0  46+0  48+0  51+0  53+0  53+0  53+0  51+0  
15463  ...  37+0  36+0  36+0  36+0  37+0  39+0  40+0  40+0  40+0  39+0  
15464  ...  36+0  37+0  37+0  37+0  36+0  34+0  33+0  33+0  33+0  34+0  

[15465 rows x 104 columns]

In [81]:
df.dtypes

sofifa_id      int64
player_url    object
short_name    object
long_name     object
age            int64
               ...  
lb            object
lcb           object
cb            object
rcb           object
rb            object
Length: 104, dtype: object

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15465 entries, 0 to 15464
Columns: 104 entries, sofifa_id to rb
dtypes: float64(17), int64(11), object(76)
memory usage: 12.3+ MB


In [83]:
df.isna().sum()

sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ... 
lb            1703
lcb           1703
cb            1703
rcb           1703
rb            1703
Length: 104, dtype: int64

In [84]:
df.shape

(15465, 104)

# Training set 70 : Testing set 30

In [85]:
X = df.iloc[:,:-1] #Target
Y = df.iloc[:,-1] #Feature

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [106]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", X_test.shape)

Dimensi X_train :  (10825, 103)
Dimensi X_train :  (4640, 103)
Dimensi y_train :  (10825,)
Dimensi y_test :  (4640, 103)


# Normalisasi

In [88]:
from sklearn.preprocessing import MinMaxScaler

In [89]:
dAngka = df["age"].astype("float64")*0.001
dAngka

0        0.027
1        0.029
2        0.030
3        0.032
4        0.028
         ...  
15460    0.017
15461    0.017
15462    0.018
15463    0.022
15464    0.041
Name: age, Length: 15465, dtype: float64

In [90]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['height_cm','age','weight_kg']])

In [91]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(6)

0         1         2
0  0.291667  0.392857  0.283333
1  0.625000  0.464286  0.500000
2  0.520833  0.500000  0.500000
3  0.833333  0.571429  0.750000
4  0.791667  0.428571  0.700000
5  0.541667  0.392857  0.516667

# Standarisasi

In [92]:
from sklearn.preprocessing import StandardScaler 

In [93]:
ss = StandardScaler()
data = np.asarray(df[['height_cm','age','weight_kg']])
Scaled_data = ss.fit_transform(data)

In [94]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("============================================")
print("\n Nilai Data setelah scaling : ") 
print(Scaled_data) 
print("Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data Sebelum scaling : 
[[169  27  67]
 [185  29  80]
 [180  30  80]
 ...
 [190  18  76]
 [180  22  70]
 [175  41  72]]
Nilai standar deviasi:  65.4086765097634

 Nilai Data setelah scaling : 
[[-1.82271149  0.48367806 -1.22812772]
 [ 0.58875487  0.9161652   0.65401534]
 [-0.16482837  1.13240876  0.65401534]
 ...
 [ 1.34233811 -1.46251404  0.0748944 ]
 [-0.16482837 -0.59753977 -0.79378702]
 [-0.9184116   3.511088   -0.50422654]]
Nilai standar deviasi:  1.0


# Data Cleaning

In [95]:
from sklearn.impute import SimpleImputer

In [96]:
df.isna().sum()

sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ... 
lb            1703
lcb           1703
cb            1703
rcb           1703
rb            1703
Length: 104, dtype: int64

# Mengubah nilai null yang punya tipe data desimal

In [97]:
imputer = SimpleImputer(strategy = 'mean')
df["height_cm"] = imputer.fit_transform(df[["age"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ... 
lb            1703
lcb           1703
cb            1703
rcb           1703
rb            1703
Length: 104, dtype: int64


# Mengubah nilai null yang punya tipe data kategorikal

In [98]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["weight_kg"] = imputer.fit_transform(df[["weight_kg"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ... 
lb            1703
lcb           1703
cb            1703
rcb           1703
rb            1703
Length: 104, dtype: int64


# Mengubah nilai null yang punya tipe data bulat

In [108]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["age"] = imputer.fit_transform(df[["age"]])
print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
sofifa_id     0
player_url    0
short_name    0
long_name     0
age           0
             ..
15404         0
15405         0
15406         0
15407         0
15408         0
Length: 15514, dtype: int64


# Data duplikat

In [99]:
df[df.duplicated()]

Empty DataFrame
Columns: [sofifa_id, player_url, short_name, long_name, age, dob, height_cm, weight_kg, nationality, club, overall, potential, value_eur, wage_eur, player_positions, preferred_foot, international_reputation, weak_foot, skill_moves, work_rate, body_type, real_face, release_clause_eur, player_tags, team_position, team_jersey_number, loaned_from, joined, contract_valid_until, nation_position, nation_jersey_number, pace, shooting, passing, dribbling, defending, physic, gk_diving, gk_handling, gk_kicking, gk_reflexes, gk_speed, gk_positioning, player_traits, attacking_crossing, attacking_finishing, attacking_heading_accuracy, attacking_short_passing, attacking_volleys, skill_dribbling, skill_curve, skill_fk_accuracy, skill_long_passing, skill_ball_control, movement_acceleration, movement_sprint_speed, movement_agility, movement_reactions, movement_balance, power_shot_power, power_jumping, power_stamina, power_strength, power_long_shots, mentality_aggression, mentality_interceptions, mentality_positioning, mentality_vision, mentality_penalties, mentality_composure, defending_marking, defending_standing_tackle, defending_sliding_tackle, goalkeeping_diving, goalkeeping_handling, goalkeeping_kicking, goalkeeping_positioning, goalkeeping_reflexes, ls, st, rs, lw, lf, cf, rf, rw, lam, cam, ram, lm, lcm, cm, rcm, rm, lwb, ldm, cdm, rdm, rwb, lb, ...]
Index: []

[0 rows x 104 columns]

In [100]:
df.drop_duplicates(inplace=True)

In [101]:
print("Setelah menggunakan fungsi drop_duplicates()") 
print("Jumlah Nilai Duplikat:",df.duplicated().sum())

Setelah menggunakan fungsi drop_duplicates()
Jumlah Nilai Duplikat: 0


# Mengubah tipe data angka menjadi kategorikal

In [102]:
from sklearn.preprocessing import OrdinalEncoder

In [103]:
encoder = OrdinalEncoder() 
df["short_nameEnc"] = encoder.fit_transform(df[["short_name"]]) 
df.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2       9014  https://sofifa.com/player/9014/arjen-robben/15...   
3      41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4     167495  https://sofifa.com/player/167495/manuel-neuer/...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   27  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   29  1985-02-05   
2          A. Robben                         Arjen Robben   30  1984-01-23   
3     Z. Ibrahimović                   Zlatan Ibrahimović   32  1981-10-03   
4           M. Neuer                         Manuel Neuer   28  1986-03-27   

   height_cm  weight_kg  nationality                 club  ...   ldm   cdm  \
0       27.0         67    Argentina         FC Barcelona  ...  62+3  62+3   
1       29.0         80     Portugal          Real Madrid  ...  63+3  63+3   
2       30.0         80  Netherlands    FC Bayern München  ...  64+3  64+3   
3       32.0         95       Sweden  Paris Saint-Germain  ...  65+3  65+3   
4       28.0         92      Germany    FC Bayern München  ...   NaN   NaN   

    rdm   rwb    lb   lcb    cb   rcb    rb short_nameEnc  
0  62+3  62+3  54+3  45+3  45+3  45+3  54+3        8320.0  
1  63+3  63+3  57+3  52+3  52+3  52+3  57+3        2775.0  
2  64+3  64+3  55+3  46+3  46+3  46+3  55+3        1005.0  
3  65+3  61+3  56+3  55+3  55+3  55+3  56+3       14479.0  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN        9651.0  

[5 rows x 105 columns]

# One Hot Encoding

In [104]:
from sklearn.preprocessing import OneHotEncoder

In [105]:
encoder = OneHotEncoder(sparse=False) 
long_nameEnc = encoder.fit_transform(df[["long_name"]]) 
long_nameEnc = pd.DataFrame(long_nameEnc) 
df = df.join(long_nameEnc) 
df 

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2           9014  https://sofifa.com/player/9014/arjen-robben/15...   
3          41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4         167495  https://sofifa.com/player/167495/manuel-neuer/...   
...          ...                                                ...   
15460     220806  https://sofifa.com/player/220806/ellis-redman/...   
15461     225509  https://sofifa.com/player/225509/aaron-collins...   
15462     217591  https://sofifa.com/player/217591/piotr-zemlo/1...   
15463     222947  https://sofifa.com/player/222947/tom-davies/15...   
15464     201197  https://sofifa.com/player/201197/paul-tisdale/...   

              short_name                            long_name  age  \
0               L. Messi       Lionel Andrés Messi Cuccittini   27   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   29   
2              A. Robben                         Arjen Robben   30   
3         Z. Ibrahimović                   Zlatan Ibrahimović   32   
4               M. Neuer                         Manuel Neuer   28   
...                  ...                                  ...  ...   
15460          E. Redman                         Ellis Redman   17   
15461         A. Collins                        Aaron Collins   17   
15462           P. Żemło                          Piotr Żemło   18   
15463          T. Davies                           Tom Davies   22   
15464         P. Tisdale                         Paul Tisdale   41   

              dob  height_cm  weight_kg  nationality                 club  \
0      1987-06-24       27.0         67    Argentina         FC Barcelona   
1      1985-02-05       29.0         80     Portugal          Real Madrid   
2      1984-01-23       30.0         80  Netherlands    FC Bayern München   
3      1981-10-03       32.0         95       Sweden  Paris Saint-Germain   
4      1986-03-27       28.0         92      Germany    FC Bayern München   
...           ...        ...        ...          ...                  ...   
15460  1996-09-26       17.0         81        Wales       Newport County   
15461  1997-06-01       17.0         57        Wales       Newport County   
15462  1995-07-10       18.0         76       Poland         Wisła Kraków   
15463  1992-04-18       22.0         70      England       Fleetwood Town   
15464  1973-01-14       41.0         72        Malta          Exeter City   

       ...  15399  15400  15401  15402 15403 15404  15405  15406  15407 15408  
0      ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
1      ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
2      ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
3      ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
4      ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
...    ...    ...    ...    ...    ...   ...   ...    ...    ...    ...   ...  
15460  ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
15461  ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
15462  ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
15463  ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  
15464  ...    0.0    0.0    0.0    0.0   0.0   0.0    0.0    0.0    0.0   0.0  

[15465 rows x 15514 columns]