In [2]:
import tensorflow as tf
import numpy as np

# Random tensor dengan shape (5,5)

In [4]:
random_tensor = np.around(tf.random.normal([5,5]))

In [5]:
random_tensor

array([[-0., -0., -2., -0., -0.],
       [ 1., -0., -0., -1., -1.],
       [-1., -0.,  1.,  0.,  1.],
       [-0., -2.,  1.,  0., -1.],
       [ 1.,  1.,  0.,  1.,  1.]], dtype=float32)

# Tensor bilangan prima dengan shape (5,5)

In [6]:
list = [[1, 2, 3, 5, 7], [11, 13, 17, 19, 23], [29, 31, 37, 41, 43], [47, 53, 59, 61, 71], [73, 79, 83, 89, 97]]

In [7]:
prime_tensor = tf.convert_to_tensor(list, dtype=tf.float32)

In [8]:
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  5.,  7.],
       [11., 13., 17., 19., 23.],
       [29., 31., 37., 41., 43.],
       [47., 53., 59., 61., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

# Dimensi random tensor

In [9]:
random_tensor.shape

(5, 5)

In [10]:
prime_tensor.shape

TensorShape([5, 5])

# Perhitungan Aritmatika dua variable

In [12]:
a = random_tensor
b = prime_tensor

jumlah = tf.add(a, b)
kurang = tf.subtract(a, b)
kali = tf.multiply(a, b)
bagi = tf.divide(a, b)
pangkat = tf.pow(a, b)

In [13]:
print(jumlah)

tf.Tensor(
[[ 1.  2.  1.  5.  7.]
 [12. 13. 17. 18. 22.]
 [28. 31. 38. 41. 44.]
 [47. 51. 60. 61. 70.]
 [74. 80. 83. 90. 98.]], shape=(5, 5), dtype=float32)


In [14]:
print(kurang)

tf.Tensor(
[[ -1.  -2.  -5.  -5.  -7.]
 [-10. -13. -17. -20. -24.]
 [-30. -31. -36. -41. -42.]
 [-47. -55. -58. -61. -72.]
 [-72. -78. -83. -88. -96.]], shape=(5, 5), dtype=float32)


In [15]:
print(kali)

tf.Tensor(
[[  -0.   -0.   -6.   -0.   -0.]
 [  11.   -0.   -0.  -19.  -23.]
 [ -29.   -0.   37.    0.   43.]
 [  -0. -106.   59.    0.  -71.]
 [  73.   79.    0.   89.   97.]], shape=(5, 5), dtype=float32)


In [16]:
print(bagi)

tf.Tensor(
[[-0.         -0.         -0.6666667  -0.         -0.        ]
 [ 0.09090909 -0.         -0.         -0.05263158 -0.04347826]
 [-0.03448276 -0.          0.02702703  0.          0.02325581]
 [-0.         -0.03773585  0.01694915  0.         -0.01408451]
 [ 0.01369863  0.01265823  0.          0.01123596  0.01030928]], shape=(5, 5), dtype=float32)


In [17]:
print(pangkat)

tf.Tensor(
[[-0.000000e+00  0.000000e+00 -8.000000e+00 -0.000000e+00 -0.000000e+00]
 [ 1.000000e+00 -0.000000e+00 -0.000000e+00 -1.000000e+00 -1.000000e+00]
 [-1.000000e+00 -0.000000e+00  1.000000e+00  0.000000e+00  1.000000e+00]
 [-0.000000e+00 -9.007199e+15  1.000000e+00  0.000000e+00 -1.000000e+00]
 [ 1.000000e+00  1.000000e+00  0.000000e+00  1.000000e+00  1.000000e+00]], shape=(5, 5), dtype=float32)


# Nilai maksimal dan Minimal dari variable random_tensor

In [18]:
print("Maksimal : ",tf.argmax(random_tensor))
print("Minimal : ",tf.argmin(random_tensor))

Maksimal :  tf.Tensor([1 4 2 4 2], shape=(5,), dtype=int64)
Minimal :  tf.Tensor([2 3 0 1 1], shape=(5,), dtype=int64)


In [19]:
print(tf.concat([random_tensor, prime_tensor],axis=0))

tf.Tensor(
[[-0. -0. -2. -0. -0.]
 [ 1. -0. -0. -1. -1.]
 [-1. -0.  1.  0.  1.]
 [-0. -2.  1.  0. -1.]
 [ 1.  1.  0.  1.  1.]
 [ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 71.]
 [73. 79. 83. 89. 97.]], shape=(10, 5), dtype=float32)


# Sorting Descending kedua tensor

In [20]:
print("Sebelum di sorting secara descending",random_tensor)
rs = tf.sort(random_tensor, direction="DESCENDING")
print("Sesudah di sorting secara descending",rs)

Sebelum di sorting secara descending [[-0. -0. -2. -0. -0.]
 [ 1. -0. -0. -1. -1.]
 [-1. -0.  1.  0.  1.]
 [-0. -2.  1.  0. -1.]
 [ 1.  1.  0.  1.  1.]]
Sesudah di sorting secara descending tf.Tensor(
[[-0. -0. -0. -0. -2.]
 [ 1. -0. -0. -1. -1.]
 [ 1.  1. -0.  0. -1.]
 [ 1. -0.  0. -1. -2.]
 [ 1.  1.  1.  1.  0.]], shape=(5, 5), dtype=float32)


In [21]:
print("Sebelum di sorting secara descending",prime_tensor)
ps = tf.sort(prime_tensor, direction="DESCENDING")
print("Sesudah di sorting secara descending",ps)

Sebelum di sorting secara descending tf.Tensor(
[[ 1.  2.  3.  5.  7.]
 [11. 13. 17. 19. 23.]
 [29. 31. 37. 41. 43.]
 [47. 53. 59. 61. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)
Sesudah di sorting secara descending tf.Tensor(
[[ 7.  5.  3.  2.  1.]
 [23. 19. 17. 13. 11.]
 [43. 41. 37. 31. 29.]
 [71. 61. 59. 53. 47.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
